<?php
    $routers=array(
        'trang-chu'=>'modules/users/home.php',
        'tat-ca-san-pham'=>'modules/users/list-all-product.php',
        'danh-sach-san-pham'=>'modules/admin/list-product.php',
        'danh-sach-don-hang'=>'modules/admin/orders.php',
        'dang-nhap'=>'modules/users/login-form.php',
        'dang-ky'=>'modules/users/register-form.php',
        'doanh-so-ban-hang'=>'modules/admin/turnover.php',
        'xu-li-xoa-san-pham'=>'modules/admin/delete-product.php',
        'them-san-pham'=>'modules/admin/add-product.php',
        'xoa-san-pham'=>'modules/admin/delete-product.php',
        'sua-san-pham'=>'modules/admin/edit-product.php',
        'san-pham'=>'modules/users/product-detail.php',
        'tin-tuc'=>'modules/users/blog.php',
        'gio-hang'=>'modules/users/cart.php',
        'hoa-don'=>'modules/users/bill.php',
        'dia-chi-nhan-hang'=>'modules/users/add-address.php',
        'xu-ly-dat-hang'=>'modules/users/order-handle.php',
        'xu-ly-them-dia-chi'=>'modules/handle/add-address.php',
        'xu-ly-xoa-dia-chi'=>'modules/handle/delete-address.php',
    )
?>
