<?php
    $routers=array(
        'trang-chu'=>'modules/users/home.php',
        'tat-ca-san-pham'=>'modules/users/list-all-product.php',
        'danh-sach-san-pham'=>'modules/admin/list-product.php',
        'danh-sach-don-hang'=>'modules/admin/orders.php',
        'dang-nhap'=>'modules/users/login-form.php',
        'dang-ky'=>'modules/users/register-form.php',
        'doanh-so-ban-hang'=>'modules/admin/turnover.php',
        'xu-li-xoa-san-pham'=>'modules/admin/delete-product.php',
        'them-san-pham'=>'modules/admin/add-product.php',
        'xoa-san-pham'=>'modules/admin/delete-product.php',
    )
?>
